apiVersion: apps/v1
kind: Deployment
metadata:
  name: la
spec:
  replicas: 1
  selector:
    matchLabels:
      app: la
  template:
    metadata:
      labels:
        app: la
    spec:
      containers:
      - image: okteto.dev/la:latest
        name: la
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "03dbcc55-564c-4138-96fc-86cdfa75dedf"
        - name: Vless_Path
          value: "/s233LV29BHGydchf"
        - name: Vmess_UUID
          value: "03dbcc55-564c-4138-96fc-86cdfa75dedf"
        - name: Vmess_Path
          value: "/s244LV29BHGydchf"
        - name: Share_Path
          value: "/share233"
