apiVersion: apps/v1
kind: Deployment
metadata:
  name: mom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mom
  template:
    metadata:
      labels:
        app: mom
    spec:
      containers:
      - image: okteto.dev/mom:latest
        name: mom
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1af7db06-a572-45da-8655-05095cb7bc73"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "1af7db06-a572-45da-8655-05095cb7bc73"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
