apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiss
  template:
    metadata:
      labels:
        app: kiss
    spec:
      containers:
      - image: okteto.dev/kiss:latest
        name: kiss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ffa9d47f-669e-45ed-84a4-ccb7d9090508"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "ffa9d47f-669e-45ed-84a4-ccb7d9090508"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
